# -*- coding: utf-8 -*-
"""movie recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5-58cz4H6uVkAhiQ5So9tuPGyEiLCiX
"""

import numpy as np
import pandas as pd

movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

movies.head(2)

movies=movies.merge(credits,on='title')

movies = movies[['id','title','overview','genres','keywords','cast','crew']]

movies['genres'].iloc[0]

# GIVEN GENRE IS IN STRING NOT LIST
# AND AST CONVERTS STRING INTO LIST
# ast.literal_eval(obj)
import ast

def convert(obj):
  genre=[]
  for i in ast.literal_eval(obj):
    genre.append(i['name'])
  return genre

movies['genres']= movies['genres'].apply(convert)

movies.head(2)

movies['keywords'].iloc[0]

movies['keywords']=movies['keywords'].apply(convert)

movies['cast'].iloc[0]

def convert3(obj):
  obj=ast.literal_eval(obj)
  genre=[]
  j=0
  for i in obj:
    if j<3:
      genre.append(i['name'])
      j+=1
    else:
      break
  return genre

# get top3 cast
movies['cast']=movies['cast'].apply(convert3)

movies.head(1)

movies['crew'].iloc[0]

def convertd(obj):
  genre=[]
  for i in ast.literal_eval(obj):
    if i['job']=="Director":
      genre.append(i['name'])
      break
  return genre

movies['crew'].isnull().sum()

movies['director']=movies['crew'].apply(convertd)



movies.isnull().sum()

movies=movies.dropna()

movies.isnull().sum()

movies['overview']=movies['overview'].apply(lambda x : x.split())

#beech ki spacing hatare

def spacing(obj):
  got=[]
  for i in obj:
    got.append(i.replace(" ",""))
  return got

movies['genres']=movies['genres'].apply(spacing)

movies['cast']=movies['cast'].apply(spacing)
movies['director']=movies['director'].apply(spacing)

movies['keywords']=movies['keywords'].apply(spacing)

movies['director']=movies['director'].apply(spacing)

movies.head()

movies['tags']=movies['genres']+movies['director']+movies['cast']+movies['keywords']+movies['overview']

df=movies[['id','title','tags']]

df['tags']=df['tags'].apply(lambda x:" ".join(x))

df['tags']=df['tags'].apply(lambda x: x.lower())

# vectorization

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

vectors=cv.fit_transform(df['tags']).toarray()

vectors

feature_names=cv.get_feature_names_out()

print(feature_names[50:90])

import nltk

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem(text):
  list=[]
  for i in text.split():
    list.append(ps.stem(i))

  return " ".join(list)

df['tags']=df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity

similarity= cosine_similarity(vectors)

def recommend(movie):
  movie_index=df[df['title']==movie].index[0]
  distance= similarity[movie_index]
  movielist=sorted(list(enumerate(distance)), reverse=True,key=lambda x:x[1])[1:6]

  for i in movielist:
    print(df.iloc[i[0]].title)

recommend('Batman')







